export const FETCH_LIST_SECCESS = "FETCH_LIST_SECCESS"
export const FETCH_LIST_ERROR = "FETCH_LIST_ERROR"

export const CHANGE_CURRENT_BOARD = "CHANGE_CURRENT_BOARD"
export const CHANGE_CURRENT_CARD = "CHANGE_CURRENT_CARD"

export const ADD_CARD_LISTID = "ADD_CARD_LISTID"
export const ADD_CARD_CONTENT = "ADD_CARD_CONTENT"
export const ADD_CARD_CLEAR = "ADD_CARD_CLEAR"

export const ADD_LIST_TITLE = "ADD_LIST_TITLE"
export const ADD_LIST_CLEAR = "ADD_CARD_CLEAR"